import { Inter } from 'next/font/google'
import Script from 'next/script';
import './globals.css'
import { SavePathProvider } from './component/savePathContext';
import { FilterProvider } from './component/curFilter';
import { AllItemsProvider } from './component/itemsContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <SavePathProvider>
      <FilterProvider>
        <AllItemsProvider>
          <html lang="en">
            <head>
              {/* 异步加载 Lottie 播放器脚本 */}
              <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" strategy="beforeInteractive" />
            </head>
            <body>
              {children}
            </body>
          </html>
        </AllItemsProvider>
      </FilterProvider>
    </SavePathProvider>
  )
}
